enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

# Start AeroSpace at login
start-at-login = true

exec-on-workspace-change = [
  "/bin/bash",
  "-c",
  "/opt/homebrew/bin/sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE",
]

[mode.main.binding]

# Disable annoying and useless "hide application" shortcut
cmd-h = []

cmd-left = 'focus left'
cmd-down = 'focus down'
cmd-up = 'focus up'
cmd-right = 'focus right'

cmd-shift-h = 'split horizontal'
cmd-shift-v = 'split vertical'

alt-f = 'fullscreen'

cmd-s = 'layout v_accordion' # 'layout stacking' in i3
alt-w = 'layout h_accordion' # 'layout tabbed' in i3

alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

cmd-enter = 'exec-and-forget ~/.local/bin/new_ghostty.sh'

cmd-1 = 'workspace 1'
cmd-2 = 'workspace 2'
cmd-3 = 'workspace 3'
cmd-4 = 'workspace 4'
cmd-5 = 'workspace 5'
cmd-6 = 'workspace 6'
cmd-7 = 'workspace 7'
cmd-8 = 'workspace 8'
cmd-9 = 'workspace 9'

cmd-shift-1 = 'move-node-to-workspace 1'
cmd-shift-2 = 'move-node-to-workspace 2'
cmd-shift-3 = 'move-node-to-workspace 3'
cmd-shift-4 = 'move-node-to-workspace 4'
cmd-shift-5 = 'move-node-to-workspace 5'
cmd-shift-6 = 'move-node-to-workspace 6'
cmd-shift-7 = 'move-node-to-workspace 7'
cmd-shift-8 = 'move-node-to-workspace 8'
cmd-shift-9 = 'move-node-to-workspace 9'

alt-shift-c = 'reload-config'

alt-r = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
if.during-aerospace-startup = false
check-further-callbacks = true
run = ['move-node-to-workspace 1']  #

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
if.during-aerospace-startup = false
check-further-callbacks = true
run = ['move-node-to-workspace 2']

[[on-window-detected]]
if.app-id = 'org.mozilla.firefox'
if.during-aerospace-startup = false
check-further-callbacks = true
run = ['move-node-to-workspace 6']

[[on-window-detected]]
if.app-id = 'us.zoom.xos'
if.during-aerospace-startup = false
check-further-callbacks = true
run = ['move-node-to-workspace 7']

[gaps]
outer.top = [
{ monitor."Built-in" = 0 },
{ monitor."DELL" = 32 },
32
]
